-- SEC-002: Flyway baseline migration.
-- Bu dosya, canlı Supabase veritabanının mevcut şemasını (2026-09-10 itibarıyla)
-- birebir yansıtır. Kaynak: Supabase SQL Editor'den information_schema.columns,
-- information_schema.table_constraints/key_column_usage, information_schema.
-- referential_constraints ve pg_indexes sorgularının CSV export'ları (pg_dump'a
-- ağ erişimi engellendiği için bu yöntemle çıkarıldı). DB'ye HENÜZ UYGULANMADI —
-- Flyway'in "baseline" mekanizmasıyla mevcut (dolu) veritabanında sadece
-- flyway_schema_history'e "bu şema zaten burada" olarak kaydedilecek; sıfırdan
-- bir ortamda ise bu SQL gerçekten çalışıp aynı şemayı oluşturacak.

-- =========================================================================
-- households (bağımsız, başka tabloya referans vermiyor)
-- =========================================================================
CREATE TABLE households (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp,
    invite_code varchar(255) NOT NULL,
    name        varchar(255) NOT NULL
);

CREATE UNIQUE INDEX uk8icf8sy14mocagr0qdqido5cs ON households (invite_code);

-- =========================================================================
-- users (households'a FK)
-- =========================================================================
CREATE TABLE users (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                  timestamp,
    email                       varchar(255) NOT NULL,
    password                    varchar(255) NOT NULL,
    name                        varchar(255),
    profile_image_url           varchar(255),
    email_verified              boolean NOT NULL DEFAULT true,
    reset_password_code         varchar(255),
    reset_password_code_expiry  timestamp,
    verification_code           varchar(255),
    verification_code_expiry    timestamp,
    fcm_token                   varchar(255),
    token_version               integer NOT NULL DEFAULT 0,
    reset_password_attempts     integer NOT NULL DEFAULT 0,
    verification_attempts       integer NOT NULL DEFAULT 0,
    notify_budget_overspend     boolean NOT NULL DEFAULT true,
    notify_budget_warning       boolean NOT NULL DEFAULT true,
    household_id                bigint,
    CONSTRAINT fklacr3nkhlm93hgc5d32ukqim9 FOREIGN KEY (household_id) REFERENCES households (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE UNIQUE INDEX uk6dotkott2kjsp8vw4d0m25fb7 ON users (email);

-- =========================================================================
-- categories (users'a FK)
-- =========================================================================
CREATE TABLE categories (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color   varchar(255),
    name    varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT fkghuylkwuedgl2qahxjt8g41kb FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX idx_categories_user_id ON categories (user_id);
CREATE UNIQUE INDEX uk_categories_user_name ON categories (user_id, name);

-- =========================================================================
-- budgets (categories + users'a FK)
-- =========================================================================
CREATE TABLE budgets (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month               integer NOT NULL,
    monthly_limit       numeric(10,2) NOT NULL,
    year                integer NOT NULL,
    category_id         bigint NOT NULL,
    user_id             bigint NOT NULL,
    overspend_notified  boolean NOT NULL DEFAULT false,
    warning_notified    boolean NOT NULL DEFAULT false,
    CONSTRAINT fkn7qib00712y8dwelmqfwis6ka FOREIGN KEY (category_id) REFERENCES categories (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fkln0tm5tgf3f9q3sp9sa5m8m7b FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX idx_budgets_category_id ON budgets (category_id);
CREATE UNIQUE INDEX ukjc7pssomn244q2bm3voc49e7w ON budgets (user_id, category_id, year, month);

-- =========================================================================
-- receipts (users + categories'a FK)
-- =========================================================================
CREATE TABLE receipts (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              timestamp,
    image_url               varchar(255),
    raw_ocr_text            text,
    receipt_date            date,
    store_name              varchar(255),
    total_amount            numeric(10,2),
    category_id             bigint,
    user_id                 bigint NOT NULL,
    split_details_json      text,
    return_deadline         date,
    return_reminder_sent    boolean NOT NULL DEFAULT false,
    warranty_expiry_date    date,
    warranty_reminder_sent  boolean NOT NULL DEFAULT false,
    CONSTRAINT fk7t0uo7yxjck29e967rny84ky4 FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk89ipq3o1n6w7p6gng9p2uiq9j FOREIGN KEY (category_id) REFERENCES categories (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX idx_receipts_category_id ON receipts (category_id);
CREATE INDEX idx_receipts_user_date ON receipts (user_id, receipt_date);

-- =========================================================================
-- receipt_items (receipts'a FK)
-- =========================================================================
CREATE TABLE receipt_items (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_name   varchar(255) NOT NULL,
    product_name      varchar(255) NOT NULL,
    quantity          numeric(10,2),
    unit_price        numeric(10,2) NOT NULL,
    receipt_id        bigint NOT NULL,
    CONSTRAINT fkmyfhuc1y0sjqe2geey8jx9nc2 FOREIGN KEY (receipt_id) REFERENCES receipts (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX idx_receipt_items_normalized_name ON receipt_items (normalized_name);
CREATE INDEX idx_receipt_items_receipt_id ON receipt_items (receipt_id);

-- =========================================================================
-- savings_goals (users'a FK)
-- =========================================================================
CREATE TABLE savings_goals (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achieved_notified   boolean NOT NULL DEFAULT false,
    created_at          timestamp,
    current_amount      numeric(10,2) NOT NULL,
    name                varchar(255) NOT NULL,
    target_amount       numeric(10,2) NOT NULL,
    target_date         date,
    user_id             bigint NOT NULL,
    CONSTRAINT fkcxl8rfkv17sumgm83nx0pl2x8 FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX idx_savings_goals_user_id ON savings_goals (user_id);
